env:
  global:
    - CC_TEST_REPORTER_ID=9a546c8a6f32931d1dc2fdbe50f8759370f3b3b93690c98597aa655ec5d7d2dc
language: ruby
rvm: 2.4.5
before_install: gem install bundler -v 1.17.3
notifications:
  - false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
scripts:
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
